POST {{base-url}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

POST {{base-url}}/auth/register
Content-Type: application/json

{
  "firstName": "{{first-name}}",
  "lastName": "{{last-name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###

PATCH {{base-url}}/auth/password
Content-Type: application/json

{
  "email": "{{email}}",
  "oldPassword": "{{password}}",
  "newPassword": "{{new-password}}"
}

###

GET {{base-url}}/auth/confirm?token={{confirmation-token}}
Content-Type: application/json

###

POST {{base-url}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

###

POST {{base-url}}/auth/reset-password
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "token": "{{reset-token}}"
}
