### Create image

POST {{base-url}}/images?albumId={{album-id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

### Get images in album

GET {{base-url}}/images?albumId={{album-id}}&pageSize=2&pageNumber=1
Authorization: Bearer {{token}}


### Get image

GET {{base-url}}/images/{{image-id}}
Authorization: Bearer {{token}}
